CAPTIVE_PORTAL_ENABLED=1
CAPTIVE_PORTAL_HTTP=http://connectivitycheck.grapheneos.network/generate_204
CAPTIVE_PORTAL_HTTPS=https://connectivitycheck.grapheneos.network/generate_204
PRIVATE_DNS=adblock.dns.mullvad.net
NTP_SERVER=pool.ntp.org
WEBVIEW=("vanadium" "aosmium" "cromite")
